# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PortaBoard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortaBoard

end

target 'PortaBoardWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortaBoardWatch

end

target 'PortaBoardWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortaBoardWatch Extension

end
